### PR TITLE
API Playground improvements

### PR DESCRIPTION
**Pull request by nschwertner**
- make the "required" fields bold
- placeholder attributes for the optional fields (from a hardcoded lookup table)
- RDF/NTriples/JSON-LD tabs
- code highlighting

### CODE REVIEW

**Comment by nschwertner** [comment]
The one issue here is that the code highlighter (http://code.google.com/p/google-code-prettify/) is a bit inefficient for large chunks of code and  hoses the browser. For now, I added an arbitrary limit on the size of the RDF-XML that triggers prettification (i.e. no prettification will be performed on "large" payloads):
https://github.com/chb/smart_sample_apps/blob/playground-improvements/static/framework/api_playground/controllers/main_controller.js#L146

The prettification on the NTripples and JSON-LD outputs is not very good. I look at a couple code prettifiers, but the results are similar (without writing custom plugins for them). So, perhaps we could limit the prettification to the RDF-XML and increase the limit on the maximum RDF-XML chunk size that can be prettified?

**Comment by jmandel** [comment]
Looking good!  A few issues I spotted:
- "N-Triples" spelling is off
- JSON-LD tab is blank for me 
- Interactive tab should provide examples for rdfquery + JSON-LD interface.  E.g.

```
> response.graph.where("?s ?p ?o.");
> response.objects.of_type.Medication
```

**Comment by nschwertner** [comment]
Super. I will address the #1 and #3 issues. For #2, could you make sure that you are using the updated version of the JS client (I made a few changes to it to support objectification in the API Playground)?

**Comment by jmandel** [comment]
I added a commit to deal with #2:  the problem was with circular references between medications and fulfillments (each points to the other, which works great in memory but fails on `JSON.stringify` (because it doesn't support circular references).

**Pull request merged**
