### PR TITLE
Mpr refactor

### PR DESCRIPTION
**Pull request by nschwertner**
Refactoring of the mpr_monitor code, including addition of many comments, removal of old code, reorganization (and simplification) of adherence test logic.

### CODE REVIEW

**Comment by nschwertner** [comment]
Thanks, Bill. @jmandel and I will try out the code.

**Comment by nschwertner** [comment]
Be my guest, if you'd like to stop by. Just keep in mind that I am currently on the other side of the big pond ;)

Ok, let me take a look and see what's going on with this branch. In the meanwhile, could you please take a look here and see if your changes are reflected in this commit:

https://github.com/chb/smart_sample_apps/commit/7afc2e274f7379b385631880d60d2479434caeb5

**Comment by nschwertner** [comment]
Hmm... I don't see any issues with the mpr-refactor branch.

What I would recommend is making sure that you have the latest branch head:

<pre>
git checkout mpr-refactor
git pull
</pre>


Then deleting any unnecessary files and directories using:

<pre>
git rm [filename or dir]
</pre>


And adding any missing files in:

<pre>
git add [filename]
</pre>


Then finally:

<pre>
git commit -a
git push
</pre>


Another possibility might be to start fresh with a new branch:

<pre>
git checkout dev
git branch mpr-refactor2
git checkout mpr-refactor2
</pre>


and then carefully applying your changes over the latest dev copy of the code. Could be a cleaner way to put all the changes together than rebasing and/or manually correcting version differences.

**Comment by nschwertner** [comment]
Doesn't look like this branch contains the latest code changes. Bill, could you please check it out and merge in your latest code from the refactoring?

**Comment by nschwertner** [comment]
Alternatively, if you have your code some place locally, you can zip it and send it to me over e-mail - I can do the merging.

**Comment by wjbosl** [comment]
The attached zip file should contain the correct and updated code, as of July. Your most recent changes will not be there, of course.

Thanks for all your support.

Bill

On 8/22/12 10:30 AM, "nschwertner" notifications@github.com wrote:

Doesn't look like this branch contains the latest code changes. Bill, could you please check it out and merge in your latest code from the refactoring?

**Comment by nschwertner** [comment]
Unfortunately, GitHUB has stripped off the attachment. Can you please send it to my work e-mail address?

**Comment by nschwertner** [comment]
Ok, thanks, Bill. I applied the changes for SMART 0.5 to your code and was able to verify it. I imported it into our main branch for the 0.5 release, so I am going to close this pull request and drop the mpr-refactor branch. At this point, I think the handoff is complete, so we will handle any future updates to the code internally.

**Comment by wjbosl** [comment]
Excellent. Thanks so much for your help all along. I hope this app is useful to others as they try to build new ones of their own.

Best,

Bill

On 8/27/12 10:12 AM, "nschwertner" notifications@github.com wrote:

Ok, thanks, Bill. I applied the changes for SMART 0.5 to your code and was able to verify it. I imported it into our main branch for the 0.5 release, so I am going to close this pull request and drop the mpr-refactor branch. At this point, I think the handoff is complete, so we will handle any future updates to the code internally.

**Pull request closed without merging**
